//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Arctic_Knowledge_Book_Store.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sale
    {
        public int ID { get; set; }
        public Nullable<int> BookID { get; set; }
        public Nullable<int> CustomerID { get; set; }
        public System.DateTime DateOfPurchase { get; set; }
        public string BillingAddress { get; set; }
        public int Quantity { get; set; }
        public decimal Amount { get; set; }
    
        public virtual Book Book { get; set; }
        public virtual Customer Customer { get; set; }
    }
}
